server {
    listen 80;
    listen [::]:80;
    server_name deverp.srvelectricals.in;
    location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host $host;
    }
    location / { return 301 https://$host$request_uri; }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name deverp.srvelectricals.in;
    ssl_certificate /home/bhickta/development/dev-frappe-bench/runtime/letsencrypt/live/deverp.srvelectricals.in/fullchain.pem;
    ssl_certificate_key /home/bhickta/development/dev-frappe-bench/runtime/letsencrypt/live/deverp.srvelectricals.in/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 50m;
    add_header X-Robots-Tag "noindex, nofollow" always;
    add_header X-SRV-Environment "development" always;
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120;
    }
}
