bind 127.0.0.1
port 11010
protected-mode yes
dir /home/bhickta/development/dev-frappe-bench/run
pidfile /home/bhickta/development/dev-frappe-bench/run/redis-queue.pid
logfile ""
maxmemory 256mb
maxmemory-policy noeviction
save ""
appendonly no
