bind 127.0.0.1
port 13010
protected-mode yes
dir /home/bhickta/development/dev-frappe-bench/run
pidfile /home/bhickta/development/dev-frappe-bench/run/redis-cache.pid
logfile ""
maxmemory 128mb
maxmemory-policy allkeys-lru
save ""
appendonly no
